# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

moy <- function(x) {
    .Call('_acpjpeg_moy', PACKAGE = 'acpjpeg', x)
}

ect <- function(x) {
    .Call('_acpjpeg_ect', PACKAGE = 'acpjpeg', x)
}

moy2 <- function(x) {
    .Call('_acpjpeg_moy2', PACKAGE = 'acpjpeg', x)
}

ect2 <- function(x) {
    .Call('_acpjpeg_ect2', PACKAGE = 'acpjpeg', x)
}

rcpp_hello_world <- function() {
    .Call('_acpjpeg_rcpp_hello_world', PACKAGE = 'acpjpeg')
}

